title = "TOML Config File of BoxSup Package"

[DATASET]
dataset = "pascal2012"
root = "/mnt/data1/datasets/image/voc/VOCdevkit/VOC2012/"
num_classes = 20

[DATASET.count]
# examined by 'cat <DATASETROOT>/ImageSets/BoxSup/train.txt'
train = 1464
# examined by 'cat <DATASETROOT>/ImageSets/BoxSup/val.txt'
val = 1449

[MCG]
num_candidates = 100
# Combine with DATASET.root
mcg_path = "MCG"
rerun_process = false

[TRAINER]
batchsize = 4
epochs = 80
num_iter = 20
optimizer = "ADAM"
image_size = 224
# Guideline: https://discuss.pytorch.org/t/guidelines-for-assigning-num-workers-to-dataloader/813 
num_worker = 18

[HYPER]
# COMMON
lr = 0.001
weight_Decay = 0
# ADAM
betas = [0.9, 0.999]
# SGD
momentum = 0.9
# StepLR
step_size = 7
gamma = 0.1

[MASKS]
# Options: ["GREEDY", "MINMAX"]
strat = "GREEDY"
