---
name: Code Quality Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
      - name: get repo
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install poetry
        uses: snok/install-poetry@v1.0.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: check directory
        run: ls -la .
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: venv
          path: .venv/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: get repo
        uses: actions/checkout@v2
      - name: Download venv
        uses: actions/download-artifact@v3
        with:
          name: venv
      - name: Unit & Coverage test with pytest
        run: poetry run pytest
  pythonlint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: get repo
        uses: actions/checkout@v2
      - name: Download venv
        uses: actions/download-artifact@v3
        with:
          name: venv
      - name: Check style with flake8
        run: poetry run flake8 boxsup_pytorch/ tests/

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: get repo
        uses: actions/checkout@v2
      - name: Download venv
        uses: actions/download-artifact@v3
        with:
          name: venv
      - name: Check format with black
        run: poetry run black --check boxsup_pytorch/ tests/

  typehint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: get repo
        uses: actions/checkout@v2
      - name: Download venv
        uses: actions/download-artifact@v3
        with:
          name: venv
      - name: Check type hinting with mypy
        run: poetry run mypy --strict --config-file=mypy.ini boxsup_pytorch/

  yamllint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: get repo
        uses: actions/checkout@v2
      - name: Download venv
        uses: actions/download-artifact@v3
        with:
          name: venv
      - name: Check yaml style with yamllint
        run: poetry run yamllint . -c yamllint-config.yml
