---
name: Code Quality Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  run-pytest-setup:
    runs-on: ubuntu-latest
    name: Run Pytest with Poetry
    steps:
      - uses: actions/checkout@v3
      - id: poetry-setup
        uses: makanu/poetry-setup-composite-action@v1
        with:
          python_version: '3.8'
          hashed_key: "venv-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}"
          poetry_command: "pytest"

  run-flake-setup:
    runs-on: ubuntu-latest
    name: Run Flake8 with Poetry
    steps:
      - uses: actions/checkout@v3
      - id: poetry-setup
        uses: makanu/poetry-setup-composite-action@v1
        with:
          python_version: '3.8'
          hashed_key: "venv-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}"
          poetry_command: "flake8 boxsup_pytorch/ tests/"

  run-black-setup:
    runs-on: ubuntu-latest
    name: Run black with Poetry
    steps:
      - uses: actions/checkout@v3
      - id: poetry-setup
        uses: makanu/poetry-setup-composite-action@v1
        with:
          python_version: '3.8'
          hashed_key: "venv-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}"
          poetry_command: "black --check boxsup_pytorch/ tests/"

  run-mypy-setup:
    runs-on: ubuntu-latest
    name: Run mypy with Poetry
    steps:
      - uses: actions/checkout@v3
      - id: poetry-setup
        uses: makanu/poetry-setup-composite-action@v1
        with:
          python_version: '3.8'
          hashed_key: "venv-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}"
          poetry_command: "mypy --strict --config-file=mypy.ini boxsup_pytorch/"

  run-yamllint-setup:
    runs-on: ubuntu-latest
    name: Run yamllint with Poetry
    steps:
      - uses: actions/checkout@v3
      - id: poetry-setup
        uses: makanu/poetry-setup-composite-action@v1
        with:
          python_version: '3.8'
          hashed_key: "venv-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}"
          poetry_command: "yamllint . -c yamllint-config.yml"
