---
name: Code Quality Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - run: ls -la
      - uses: actions/checkout@v2
      - run: ls -la
      - run: which python
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: ls -la
      - run: which python

