---
name: Code Quality Checks

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7]

    runs-on: ${{ matrix.os }}
    steps:
      - id: poetry-setup
        uses: makanu/poetry-setup-composite-action@v2
        with:
          python_version: ${{ matrix.python }}
      - name: Unit & Coverage test with pytest
        run: poetry run pytest

  pythonlint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check style with flake8
        run: poetry run flake8 boxsup_pytorch/ tests/

  format:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check format with black
        run: poetry run black --check boxsup_pytorch/ tests/

  typehint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check type hinting with mypy
        run: poetry run mypy --strict --config-file=mypy.ini boxsup_pytorch/

  yamllint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check yaml style with yamllint
        run: poetry run yamllint . -c yamllint-config.yml
